- name : create ec2 and r53 records
  hosts : all
  connection : local
  vars:
    sg_id : sg-060e96adf2fe4b45c
    ami_id : ami-0220d79f3f480ecf5
    domain : smttechnologies.online
    Instances :
    -  mongodb
    -  catalogue
    Env : dev

     
  tasks :
    - name: create ec2
      amazon.aws.ec2_instance:
        # key_name: "ansible-ec2"
        # region: "us-east-1"
        security_group: "{{ sg_id }}"
        instance_type: "t3.micro"
        image_id: "{{ ami_id }}"
        name: "{{ item }}-{{ Env }}"
        tags:
          Project: "roboshop"
          Component: "{{ item }}"
          Environment: "{{ Env }}"
          Name: "{{ item }}"
      loop: "{{ Instances }}"
      register: ec2_output
    - name : print ec2 output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"  
      

    - name : create r53 record
      amazon.aws.route53:
        state: present
        zone: "{{ domain }}"
        record: "{{ item.item }}.{{ Env }}.{{ domain }}" #mongodb-dev.smttechnologies.online
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}" #mongodb-dev.smttechnologies.online will point to private ip address of ec2 instance.Index 0 because we are creating only one instance per component
      loop: "{{ ec2_output.results }}"